### ISSUE TITLE
Jig is very large

### ISSUE THREAD

**Issue by jakobtolstrup** [RobMink/Babybelt#4]
The jig.stl file results in a Ø196mm or 616mm long belt. Shouldn't the diameter be around 91mm

**Comment by RobMink** [comment]
Yep, you are 100% correct, it was way too large.  Fixed now, sorry about that!  It is 98.61 MM diameter and 125 MM tall.

**Comment by RobMink** [comment]
Updated file, commented!

**Comment by jakobtolstrup** [comment]
Awesome, thanks
