### ISSUE TITLE
Discord Link Invalid

### ISSUE THREAD

**Issue by hanzov69** [RobMink/Babybelt#5]
Hey we saw you today at ERRF, we're super stoked to build our own Babybelts!
Your discord link is invalid/expired though

**Comment by RobMink** [comment]
Thanks!  Did you read the text after the link about removing the BB to fool spam bots?  I just tested it and it seems to work for me, but I am already in the server, so I could be wrong.

**Comment by hanzov69** [comment]
womp womp. Reading fail on my part (or I'm a spam bot) ;)
