### ISSUE TITLE
Need a link for a full STL/OBJ package

### ISSUE THREAD

**Issue by inspectionsbybob** [RobMink/Babybelt#6]
Looking at the files, I was hoping there was a link somewhere to download  -ALL- the STLs or OBJ files at once...

**Comment by drdelaney** [comment]
From the main page, click on the down arrow on the green "Code" button. Click "Download ZIP."
This will download the entire branch of what branch you have selected (by default, it is main, but it looks like there are others).

**Comment by RobMink** [comment]
As noted by @drdelaney, also full step file has been in there for a while....
